[package]

name    = "p2d"
version = "0.0.1"
authors = [ "Jeff Olson <olson.jeffery@gmail.com>" ]

[lib]

name       = "p2d"
path       = "src/p2d/lib.rs"

[dependencies.uuid]
git = "https://github.com/rust-lang/uuid"

[dependencies.ecs]
git = "https://github.com/HeroesGrave/ecs-rs"